### ISSUE TITLE
[BUG] - URLs don't play

### ISSUE THREAD

**Issue by JarzaClay** [Mirasaki/mirasaki-music-bot#181] opened 2024-08-30 17:20 UTC
**Describe the bug**
When I play a, for example, YouTube URL, it just skips all videos

**To Reproduce**
1. Go to music channel
2. /play a URL
3. It skips it

**Expected behavior**
It plays

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Version Latest

**Additional context**

**Comment by Mirasaki** [comment] 2024-08-30 19:18
Hey there. YouTube is no longer supported. It's also been removed from the list of providers in the README, why did you think YouTube was supported?

We supported it in the past, but have removed the support since YouTube is actively fighting bot automation of their platform.

**Comment by Mirasaki** [comment] 2024-09-02 21:00
Closing as this is not a bug :)

**Closed by Mirasaki** 2024-09-02 21:00 UTC
Labels: wontfix

**Comment by JarzaClay** [comment] 2024-09-05 01:08
I apologize, I had previously run youtube videos just fine using this bot, so I just assumed that it would continue to work. I understand that you cannot fight against such a large company, and honestly, this has to be some sort of monopolizing, anti-competitive behavior from youtube. It's sad to see so many open-source project lose features, or even die, just because youtube isn't willing to see the life in them, and decided ad revenue is more important than an enthusiastic team of unpaid, passionate developers.

**Comment by Mirasaki** [comment] 2024-09-05 07:59
I couldn't agree more with your statement. The open-source community is fighting a losing battle on this, and it's just sad. Ad-revenue is more important to them than fostering a collaborative open-source community - and all that with no alternative to YouTube in sights.
